# Encoder parameters
network: [
  {in_channel: 3, out_channel: 32, kernel_size: 3, stride: 1, padding: 1},
  {in_channel: 32, out_channel: 16, kernel_size: 3, stride: 1, padding: 1},
  {in_channel: 16, out_channel: 8, kernel_size: 3, stride: 1, padding: 1},
  {in_channel: 8, out_channel: 1, kernel_size: 1, stride: 1, padding: 0}
]
encoding_dim: 100
learning_rate: 0.0002
batch_size: 128
epochs: 120
data_path: ~/ActionBranchingDQN/new_gripper_onfloor_imgs.pkl
